services:
  karynos-db:
    container_name: "${KARYNOS_DB_SERVER_NAME:-karynos-db}"
    image: postgres:17.5
    restart: unless-stopped
    networks:
      - karynos-network
    environment:
      POSTGRES_USER: "${KARYNOS_DB_USER:-karynos}"
      POSTGRES_PASSWORD: "${KARYNOS_DB_PASSWORD:-karynos}"
      POSTGRES_DB: "${KARYNOS_DB_NAME:-karynos}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${KARYNOS_DB_USER:-karynos} -d ${KARYNOS_DB_NAME:-karynos}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ../../db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ../../db-data/postgres:/var/lib/postgresql/data

  db-csv-import:
    image: karynos/be-python-base:latest
    container_name: db-csv-import
    restart: "no"
    networks:
      - karynos-network
    depends_on:
      karynos-db:
        condition: service_healthy
    environment:
      POSTGRES_USER: "${KARYNOS_DB_USER:-karynos}"
      POSTGRES_PASSWORD: "${KARYNOS_DB_PASSWORD:-karynos}"
      POSTGRES_DB: "${KARYNOS_DB_NAME:-karynos}"
      POSTGRES_SERVER: "${KARYNOS_DB_SERVER_NAME:-karynos-db}"
      POSTGRES_PORT: "${KARYNOS_DB_PORT:-5432}"
      CSV_IMPORT_CONFIG_JSON: "/opt/db_import/table_sources.json"
      CSV_IMPORT_SKIP_IF_TABLE_HAS_DATA: "true"
    volumes:
      - ../../db/import:/opt/db_import:ro
    command: ["python", "/opt/db_import/import_from_gdrive.py"]

  backend-app:
    container_name: backend-app
    build:
      context: ../..
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - karynos-network
    depends_on:
      karynos-db:
        condition: service_healthy
      db-csv-import:
        condition: service_completed_successfully
    env_file:
      - ../../.env.local
    environment:
      POSTGRES_USER: "${KARYNOS_DB_USER:-karynos}"
      POSTGRES_PASSWORD: "${KARYNOS_DB_PASSWORD:-karynos}"
      POSTGRES_DB: "${KARYNOS_DB_NAME:-karynos}"
      POSTGRES_SERVER: "${KARYNOS_DB_SERVER_NAME:-karynos-db}"
      POSTGRES_PORT: "${KARYNOS_DB_PORT:-5432}"
      DATABASE_URL: "postgresql://${KARYNOS_DB_USER:-karynos}:${KARYNOS_DB_PASSWORD:-karynos}@${KARYNOS_DB_SERVER_NAME:-karynos-db}:${KARYNOS_DB_PORT:-5432}/${KARYNOS_DB_NAME:-karynos}"
      CHROMA_PERSIST_DIRECTORY: "/app/ChromaDB"
      CHROMA_JOB_COLLECTION: "job_vector_db"
    ports:
      - "8000:8000"
    volumes:
      - ../..:/app
      - prisma-cache:/var/cache/karynos
    command: ["sh", "/app/scripts/start-backend-dev.sh"]

networks:
  karynos-network:
    driver: bridge

volumes:
  prisma-cache: