services:
  # Job Service
  job-db:
    container_name: "${JOB_DB_SERVER_NAME}" 
    image: postgres:17.5
    ports:
      - "5432:5432"
    networks:
      - karynos-network
    env_file:
      - ../../services/job_service/.job_env
    volumes:
      - ../../services/job_service/db/:/docker-entrypoint-initdb.d/
      - ../../services/job_service/db-data:/var/lib/postgresql/data

  job-service:
    container_name: "job-service"
    build:
      context: ../../services/job_service
    # ports:
    #   - "${JOB_SERVICE_HOST_PORT}:${JOB_SERVICE_DOCKER_PORT}"
    networks:
      - karynos-network
    depends_on:
      - job-db
    env_file:
      - ../../services/job_service/.job_env
    environment:
      - "POSTGRES_SERVER=${JOB_DB_SERVER_NAME}"
    volumes:
      - ../../services/job_service/app:/app
      - ../../shared:/app/shared
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${JOB_SERVICE_DOCKER_PORT}", "--reload"]

  # Mentor Service
  mentor-db:
    container_name: "${MENTOR_DB_SERVER_NAME}" 
    image: postgres:17.5
    networks:
      - karynos-network
    env_file:
      - ../../services/mentor_service/.mentor_env
    volumes:
      - ../../services/mentor_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../services/mentor_service/db-data:/var/lib/postgresql/data

  mentor-service:
    container_name: "mentor-service"
    build:
      context: ../../services/mentor_service
    # ports:
    #   - "${MENTOR_SERVICE_HOST_PORT}:${MENTOR_SERVICE_DOCKER_PORT}"
    networks:
      - karynos-network
    depends_on:
      - mentor-db
    env_file:
      - ../../services/mentor_service/.mentor_env
    environment:
      - "POSTGRES_SERVER=${MENTOR_DB_SERVER_NAME}"
    volumes:
      - ../../services/mentor_service/app:/app
      - ../../shared:/app/shared
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${MENTOR_SERVICE_DOCKER_PORT}", "--reload"]

  # Dreamer Service
  dreamer-db:
    container_name: "${DREAMER_DB_SERVER_NAME}" 
    image: postgres:17.5
    networks:
      - karynos-network
    env_file:
      - ../../services/dreamer_service/.dreamer_env
    volumes:
      - ../../services/dreamer_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../services/dreamer_service/db-data:/var/lib/postgresql/data

  dreamer-service:
    container_name: "dreamer-service"
    build:
      context: ../../services/dreamer_service
    # ports:
    #   - "${DREAMER_SERVICE_HOST_PORT}:${DREAMER_SERVICE_DOCKER_PORT}"
    networks:
      - karynos-network
    depends_on:
      - dreamer-db
    env_file:
      - ../../services/dreamer_service/.dreamer_env
    environment:
      - "POSTGRES_SERVER=${DREAMER_DB_SERVER_NAME}"
    volumes:
      - ../../services/dreamer_service/app:/app
      - ../../shared:/app/shared
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${DREAMER_SERVICE_DOCKER_PORT}", "--reload"]

  # Textbook Service
  # textbook-db:
  #   container_name: "${TEXTBOOK_DB_SERVER_NAME}" 
  #   image: postgres:17.5
  #   networks:
  #     - karynos-network
  #   env_file:
  #     - ../../services/textbook_service/.textbook_env
  #   volumes:
  #     - ../../services/textbook_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ../../services/textbook_service/db-data:/var/lib/postgresql/data

  # textbook-service:
  #   container_name: "textbook-service"
  #   build:
  #     context: ../../services/textbook_service
  #   ports:
  #     - "${TEXTBOOK_SERVICE_HOST_PORT}:${TEXTBOOK_SERVICE_DOCKER_PORT}"
  #   networks:
  #     - karynos-network
  #   depends_on:
  #     - textbook-db
  #   env_file:
  #     - ../../services/textbook_service/.textbook_env
  #   environment:
  #     - "POSTGRES_SERVER=${TEXTBOOK_DB_SERVER_NAME}"
  #   volumes:
  #     - ../../services/textbook_service/app:/app
  #     - ../../shared:/app/shared
  #   command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${TEXTBOOK_SERVICE_DOCKER_PORT}", "--reload"]

  # Chat Service
  chat-db:
    container_name: "${CHAT_DB_SERVER_NAME}" 
    image: postgres:17.5
    networks:
      - karynos-network
    env_file:
      - ../../services/chat_service/.chat_env
    volumes:
      - ../../services/chat_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../services/chat_service/db-data:/var/lib/postgresql/data

  chat-service:
    container_name: "chat-service"
    build:
      context: ../../services/chat_service
    # ports:
    #   - "${CHAT_SERVICE_HOST_PORT}:${CHAT_SERVICE_DOCKER_PORT}"
    networks:
      - karynos-network
    depends_on:
      - chat-db
    env_file:
      - ../../services/chat_service/.chat_env
    environment:
      - "POSTGRES_SERVER=${CHAT_DB_SERVER_NAME}"
    volumes:
      - ../../services/chat_service/app:/app
      - ../../shared:/app/shared
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${CHAT_SERVICE_DOCKER_PORT}", "--reload"]

  # Organization Service
  organization-db:
    container_name: "${ORGANIZATION_DB_SERVER_NAME}" 
    image: postgres:17.5
    networks:
      - karynos-network
    env_file:
      - ../../services/organization_service/.organization_env
    volumes:
      - ../../services/organization_service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../../services/organization_service/db-data:/var/lib/postgresql/data

  organization-service:
    container_name: "organization-service"
    build:
      context: ../../services/organization_service
    # ports:
    #   - "${ORGANIZATION_SERVICE_HOST_PORT}:${ORGANIZATION_SERVICE_DOCKER_PORT}"
    networks:
      - karynos-network
    depends_on:
      - organization-db
    env_file:
      - ../../services/organization_service/.organization_env
    environment:
      - "POSTGRES_SERVER=${ORGANIZATION_DB_SERVER_NAME}"
    volumes:
      - ../../services/organization_service/app:/app
      - ../../shared:/app/shared
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${ORGANIZATION_SERVICE_DOCKER_PORT}", "--reload"]

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ../../nginx/dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - job-service
      - mentor-service
      - dreamer-service
      - chat-service
      - organization-service
    networks:
      - karynos-network

networks:
  karynos-network:
    driver: bridge