services:
  app:
    container_name: "auth-service"
    build: .
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - auth-db
    volumes:
      - ./app:/app
    env_file:
      - .env_dev
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  auth-db:
    container_name: "auth-db" 
    image: postgres:17.5
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env_dev
    volumes:
      - ./test/db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local