services:
  karynos-db:
    container_name: "${POSTGRES_SERVER:-karynos-db}"
    image: postgres:17.5
    restart: unless-stopped
    networks:
      - karynos-network
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-karynos}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-karynos}"
      POSTGRES_DB: "${POSTGRES_DB:-karynos}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-karynos} -d ${POSTGRES_DB:-karynos}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ../../db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ../../db-data/postgres:/var/lib/postgresql/data

  backend-app:
    container_name: backend-app
    image: karynos/be-app:latest
    restart: unless-stopped
    networks:
      - karynos-network
    depends_on:
      karynos-db:
        condition: service_healthy
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    volumes:
      - ../../ChromaDB:/app/ChromaDB

networks:
  karynos-network:
    driver: bridge
