events {}

http {
  server {
    listen 80;

    location /job/ {
      proxy_pass http://job-service:8000/;
    }

    location /mentor/ {
      proxy_pass http://mentor-service:8000/;
    }

    location /dreamer/ {
      proxy_pass http://dreamer-service:8000/;
    }

    location /chat/ {
      proxy_pass http://chat-service:8000/;
    }

    location /organization/ {
      proxy_pass http://organization-service:8000/;
    }
  }
}
