services:
  app:
    container_name: "archive-service"
    build: .
    ports:
      - "${HOST_PORT}:${DOCKER_PORT}"
    networks:
      - karynos-network
    depends_on:
      - archive-db
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ../../shared:/app/shared
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${DOCKER_PORT}", "--reload"]

  archive-db:
    container_name: "archive-db" 
    image: postgres:17.5
    networks:
      - karynos-network
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - .env
    volumes:
      - ./test/db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local

networks:
  karynos-network:
    external: true